name: CI

# mcr.microsoft.com/mssql/server:2022-latest

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
      name: gcc
      runs-on: ubuntu-latest
      container:
        image: mcr.microsoft.com/mssql/server:2022-latest

      steps:
      - name: hello
        run: |
          echo 123
      
