name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
      name: pday
      runs-on: ubuntu-latest
      env:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "ProgrammersDay"
      container:
        image: mcr.microsoft.com/mssql/server:2022-latest

      steps:
      - name: say hello
        run: |
          /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "ProgrammersDay" query "SELECT DATEADD(DAY, 256, '2023-12-31')"
      
